/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.jjjjj;

import javax.swing.JFrame;
import javax.swing.JInternalFrame;

/**
 *
 * @author Juan Diego Roman
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private VentanaCandidatoCrear ventanaCandidatoCrear;
    private VentanaCandidatoModificar ventanaCandidatoModificar;
    private VentanaCandidatoEliminar ventanaCandidatoEliminar;
    private VentanaCandidatoListar ventanaCandidatoListar;

    private VentanaDignidadCrear ventanaDignidadCrear;
    private VentanaDignidadModificar ventanaDignidadModificar;
    private VentanaDignidadEliminar ventanaDignidadEliminar;
    private VentanaDignidadListar ventanaDignidadListar;

    private VentanaEleccionCrear ventanaEleccionCrear;
    private VentanaEleccionModificar ventanaEleccionModificar;
    private VentanaEleccionEliminar ventanEleccionEliminar;
    private VentanaEleccionListar ventanaEleccionListar;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane2 = new javax.swing.JDesktopPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 734, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 435, Short.MAX_VALUE)
        );

        jMenu1.setText("Eleccion");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Crear");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Modificar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Eliminar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Listar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Dignidad");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem5.setText("Crear");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Modificar");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Eliminar");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuItem8.setText("Listar");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Candidato");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItem9.setText("Crear");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem9);

        jMenuItem10.setText("Modificar");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem10);

        jMenuItem11.setText("Eliminar");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem11);

        jMenuItem12.setText("Listar");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem12);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        this.ventanaDignidadListar = new VentanaDignidadListar();

        ventanaDignidadListar.setClosable(true);
        ventanaDignidadListar.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ventanaDignidadListar.setVisible(true);
        ventanaDignidadListar.setIconifiable(true);

        this.jDesktopPane1.add(ventanaDignidadListar);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.ventanaEleccionCrear = new VentanaEleccionCrear();

        ventanaEleccionCrear.setClosable(true);
        ventanaEleccionCrear.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ventanaEleccionCrear.setVisible(true);
        ventanaEleccionCrear.setIconifiable(true);

        this.jDesktopPane1.add(ventanaEleccionCrear);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        this.ventanaEleccionListar = new VentanaEleccionListar();

        ventanaEleccionListar.setClosable(true);
        ventanaEleccionListar.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ventanaEleccionListar.setVisible(true);
        ventanaEleccionListar.setIconifiable(true);

        this.jDesktopPane1.add(ventanaEleccionListar);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        this.ventanaEleccionCrear = new VentanaEleccionCrear();

        ventanaEleccionCrear.setClosable(true);
        ventanaEleccionCrear.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ventanaEleccionCrear.setVisible(true);
        ventanaEleccionCrear.setIconifiable(true);

        this.jDesktopPane1.add(ventanaEleccionCrear);

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        this.ventanaCandidatoCrear = new VentanaCandidatoCrear();

        ventanaCandidatoCrear.setClosable(true);
        ventanaCandidatoCrear.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ventanaCandidatoCrear.setVisible(true);
        ventanaCandidatoCrear.setIconifiable(true);

        this.jDesktopPane1.add(ventanaCandidatoCrear);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        this.ventanaCandidatoEliminar = new VentanaCandidatoEliminar();

        ventanaCandidatoEliminar.setClosable(true);
        ventanaCandidatoEliminar.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ventanaCandidatoEliminar.setVisible(true);
        ventanaCandidatoEliminar.setIconifiable(true);

        this.jDesktopPane1.add(ventanaCandidatoEliminar);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        this.ventanaCandidatoModificar = new VentanaCandidatoModificar();

        ventanaCandidatoModificar.setClosable(true);
        ventanaCandidatoModificar.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ventanaCandidatoModificar.setVisible(true);
        ventanaCandidatoModificar.setIconifiable(true);

        this.jDesktopPane1.add(ventanaCandidatoModificar);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
        this.ventanaDignidadCrear = new VentanaDignidadCrear();

        ventanaDignidadCrear.setClosable(true);
        ventanaDignidadCrear.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ventanaDignidadCrear.setVisible(true);
        ventanaDignidadCrear.setIconifiable(true);

        this.jDesktopPane1.add(ventanaDignidadCrear);
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        this.ventanaDignidadModificar = new VentanaDignidadModificar();

        ventanaDignidadModificar.setClosable(true);
        ventanaDignidadModificar.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ventanaDignidadModificar.setVisible(true);
        ventanaDignidadModificar.setIconifiable(true);

        this.jDesktopPane1.add(ventanaDignidadModificar);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        this.ventanaDignidadEliminar = new VentanaDignidadEliminar();

        ventanaDignidadEliminar.setClosable(true);
        ventanaDignidadEliminar.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ventanaDignidadEliminar.setVisible(true);
        ventanaDignidadEliminar.setIconifiable(true);

        this.jDesktopPane1.add(ventanaDignidadEliminar);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed

        // TODO add your handling code here:
        this.ventanaCandidatoListar = new VentanaCandidatoListar();

        ventanaCandidatoListar.setClosable(true);
        ventanaCandidatoListar.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ventanaCandidatoListar.setVisible(true);
        ventanaCandidatoListar.setIconifiable(true);

        this.jDesktopPane1.add(ventanaCandidatoListar);


    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        this.ventanaDignidadCrear = new VentanaDignidadCrear();

        ventanaDignidadCrear.setClosable(true);
        ventanaDignidadCrear.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ventanaDignidadCrear.setVisible(true);
        ventanaDignidadCrear.setIconifiable(true);

        this.jDesktopPane1.add(ventanaDignidadCrear);

    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        this.ventanaEleccionModificar = new VentanaEleccionModificar();

        ventanaEleccionModificar.setClosable(true);
        ventanaEleccionModificar.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ventanaEleccionModificar.setVisible(true);
        ventanaEleccionModificar.setIconifiable(true);

        this.jDesktopPane1.add(ventanaEleccionModificar);


    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        this.ventanEleccionEliminar = new VentanaEleccionEliminar();

        ventanEleccionEliminar.setClosable(true);
        ventanEleccionEliminar.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ventanEleccionEliminar.setVisible(true);
        ventanEleccionEliminar.setIconifiable(true);

        this.jDesktopPane1.add(ventanEleccionEliminar);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables
}
